# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy EventHub
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'arm-devops-sandbox-asc'
    subscriptionId: '45678783-8214-4a06-b674-459fc609b72c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'learning-danielwellner-rg'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm-resources/arm-eventhub.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm-resources/azure-resources.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'EventHubArmOutputs'

- task: PowerShell@2
  displayName: Propagate EventHub ARM Outputs
  inputs:
    targetType: 'filePath'
    filePath: $(Build.SourcesDirectory)/tasks/ReadOutputParameters.ps1
    arguments: -ArmOutputString '$(EventHubArmOutputs)'
                      
- powershell: echo 'Producer is $(alarmProducerConnectionString)'
- powershell: echo 'Consumer is $(alarmConsumerConnectionString)'
                      
